n = int(input('Digite seu número'))

print('Vezes um {}'. format(n*1))
print('Vezes dois {}'. format(n*2))
print('Vezes três {}'. format(n*3))
print('Vezes quatro {}'. format(n*4))
print('Vezes Cinco {}'. format(n*5))
print('Vezes Seis {}'. format(n*6))
print('Vezes Sete {}'. format(n*7))
print('Vezes Oito {}'. format(n*8))
print('Vezes Nove {}'. format(n*9))
print('Vezes Dez {}'. format(n*10))