#   ESTRUTURA SIMILAR A TUPLAS, PORÉM LISTAS PODEM SER MUTÁDAS
# APPEND(ANDICIONAR ELEMENTO AO FINAL DA LISTA)
#   INSERT(0, 'LANCHE) ADICIONA O ELEMENTO NO INICIO DA LISTA
# DEL(LANCHE[3]) ELIMINAR
# LANCHE.POP(LANCHE) ELIMINAR O ÚLTIMO MAS PODE POR O INEM QUE QUER ELIMINAT
# LANCHE.REMOVE(LANCHE) ELIMINA PELO NOME DO ELEMENTO
# IF PIZZA IN LANCHE: SE A PIZZA ESTIVER DENTRO DE LANCHES
#       LANCHE.REMOVE(PIZZA) ESTRUTURA PARA TESTE
#    valores = list (range(4,11)) contagem dos números
#   valores.sort() coloca em ordem
#   vaores.sort(reverse = True) valores ordenados em reverso
#   len(valores) quantos elementos tem aqui
