import math
al = float(input('Digite o ângulo que você deseja: '))
math.radians(al)
seno = math.sin(math.radians(al))
ceno = math.cos(math.radians(al))
tan = math.tan(math.radians(al))
print(f'O ângulo de {al} tem o SENO de {seno:.2f}')
print(f'O ângulo de {al} tem o COSSENO de {ceno:.2f}')
print(f'O ângulo de {al} tem o TANGENO de {tan:.2f}')
#print(f'O ângulo de {a} tem o SENO de {math.sen(a)}')