n=int(input('Me fale um valor '))
print('''A tabuada desse valor é,
 1 x {} = {},
 2 x {} = {},
 3 x {} = {},
 4 x {} = {},
 5 x {} = {}, 
 6 x {} = {},
 7 x {} = {},
 8 x {} = {},
 9 x {} = {},
10 x {} = {}'''.format(n,n*1,n,n*2,n,n*3,n,n*4,n,n*5,n,n*6,n,n*7,n,n*8,n,n*9,n,n*10))