nome = input('Qual seu nome completo?').strip()
nomeM = nome.upper()
nomem = nome.lower()
nomeespaço = nome.replace(' ', '')
conta = (len(nomeespaço))
print('Seu nome em letra maiuscula e; {}'.format(nomeM))
print(nomem)
separado = nome.split()
print(nome[0])