x = (input('Digite algo: '))
print('Tipo primitivo: ', type(x))
print('Só tem espaços? ',x.isspace())
print('É um número? ',x.isnumeric())
print('É alfabético? ',x.isalpha())
print('É alfanumérico? ',x.isalnum())
print('Está só em maiúsculo? ',x.isupper())
print('Está só em minúsculas? ',x.islower())
print('Está capitalizada? ',x.istitle())