a = input(str('Digite algo:'))
print('O tipo primitivo desse valor é:', type(a ))
print('So tem espaços?', a.isspace())
print('É um numero?', a.isnumeric())
print('É letra', a.isalpha())
print('É fanumerico', a.isalnum())
print('Esta em maiuscula', a.isupper)
print('É uma minuscula',a.islower())
print('É está capitalizada', a.istitle())