nome = input('Qual o seu nome completo? ')
maiusculo = nome.upper()
minusculo = nome.lower()
espacos = nome.count('')
indice = format(len(nome.replace(' ', '')))
primeiron = nome.split()
print(f'Seu nome com todas as letras maiúsculas: {maiusculo}')
print(f'Seu nome com todas as letras minúsculas: {minusculo}')
print(f'Seu nome possui {indice} letras')
print(f'Seu primento nome tem {len(primeiron[0])} letras')