n = int(input('Escolha um número: '))
n1=n*2
n2=n*3
n3=n*4
n4=n*5
n5=n*6
n6=n*7
n7=n*8
n8=n*9
n9=n*10 
print('A tabuada desse número é:')
print('{}*2={}'.format(n,n1))
print('{}*3={}'.format(n,n2))
print('{}*4={}'.format(n,n3))
print('{}*5={}'.format(n,n4))
print('{}*6={}'.format(n,n5))
print('{}*7={}'.format(n,n6))
print('{}*8={}'.format(n,n7))
print('{}*9={}'.format(n,n8))
print('{}*10={}'.format(n,n9))
