nome = input('Qual o seu nome completo? ')
nomeMaior = (nome.upper())
print('Seu nome completo em maiúsculo é: {}'.format(nomeMaior))
nomeMenor = (nome.lower())
print('Seu nome completo em minúsculo é: {}'.format(nomeMenor))
numeroTotal = (nome.replace(' ', ''))
numeroSemEspaco = (len(numeroTotal))
print('A quantidade de letras no seu nome é: {}'.format(numeroSemEspaco))
primeroNome = (nome.split())
primeroNomeLetras = (len(primeroNome[0]))
print('A quantidade de letras no primeiro nome é: {}'.format(primeroNomeLetras))