nome =input("qual e o seu nome? ")
print('Prazer em te conhcer {:=^20}!!!!!'.format(nome))
#end , /n (comandos para finalizar e ter quebra de linha)
a1=int(input('um valor '))
a2=int(input('outro valor '))
print('A soma de {}'.format(a1+a2))
print('A divisao de {}'.format(a1/a2))
print('A multiplicação de {}'.format(a1*a2))
print('A elevação ao quadrado e {}'.format(a1**a2))
print('A divisão inteira e {}'.format(a1//a2))
print('A divisão a parte e {}'.format(a1%a2))
