nome = input('Qual seu nome completo? ').strip()
print('Analisando seu nome...')
print('Seu nome em MAIÚSCULO é {}'.format(nome.upper()))
print('Seu nome em MINÚSCULO é {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras'.format(len(nome.replace(" ", ""))))
#print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))
separa = nome.split()
print('Seu primeiro nome é {} e tem {} letras'.format(separa[0], len(separa[0])))