num = int(input('colo que o numero: '))
numeroStr = str(num)
print('Analizando o numero {}'.format(num))
print('Unindade {}'.format(n[3]))
print('Dezena {}'.format(n[2]))
print('Centena {}'.format(n[1]))
print('Milhar {}' .format(n[0]))