frase = (input('Digite uma frase qualquer: ')).upper()
quantidade = frase.count('A')
posicaoInicial = frase.find('A')
posicaoFinal = frase.rfind('A')
print (f'A letra A aparece {quantidade} vezes ')
print (f'A primeira letra A aparece na posição {posicaoInicial} ')
print (f'A letra A aparece pela última vez na posição {posicaoFinal} ')