nome = (input('Qual é o seu nome completo? '))
maiuscula = nome.upper()
minuscula = nome.lower()
quantidadedeletras = nome.replace(' ', '')
print (maiuscula)
print (minuscula)
print (quantidadedeletras)
print (len(quantidadedeletras))