times= ('Flamengo', 'palmeiras', 'corinthias ', 'sp' ,'Argentina', 'ZIca', 'r' , 'we')
print(f'lista brasileirão{times}')
print(f'5 primeiros {times[0:5]}')
print(f'4 ultimos {times[-4]}')
print(f'em ordem alfabetica {sorted(times)}')
print(f'chapecoense{times.index("sp")+1}posição')