n1=str(input('Digite qualquer coisa:'))
print('qual o tipo?', type (n1))
print('é alfanumerico', n1.isalnum()) 
print('esta em ordem alfabética', n1.isalpha())
print('é uma ACSII',n1.isascii())
print('todos são decimais',n1.isdecimal())
print('é um numero decimal',n1.isdigit())
print('é um elemento de indentificação',n1.isidentifier())
print('está em minusculo',n1.islower())
print('é um numero',n1.isnumeric())
print('tem possibilidade de imprimir?', n1.isprintable())
print('só tem espaços', n1.isspace())
print('esta capitalizadas', n1.istitle())
print('estão todas em maiúsculo',n1.isupper())