n1=str(input('Digite algo:'))

print('Qual seu tipo? ', type (n1))
print('É alfanumerico?', n1.isalnum()) 
print('É uma alfabetico?', n1.isalpha())
print('É uma ACSII?',n1.isascii())
print('São todos decimais?',n1.isdecimal())
print('É um numero decimal?',n1.isdigit())
print('É um elemento de indentificação?',n1.isidentifier())
print('Esta em minusculo?',n1.islower())
print('É um numero?',n1.isnumeric())
print('É imprimivel?', n1.isprintable())
print('Só tem espaços?', n1.isspace())
print('Esta capitalizada?', n1.istitle())
print('Estão todas em maiusculo?',n1.isupper())
