spring:
  application:
    name: Seção 3 library
  datasource:
    url: jdbc:postgresql://localhost:5432/Library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true