nome= str(input('Digite seu nome completo: '))
print('Analisando seu nome...')
print('Seu nome em maiúsculas é: {}'.format(nome.upper()))
print('Seu nome em minúsculas é: {}'.format(nome.lower()))
nomeSemEspaços = len(nome)-nome.count(' ')
print('Seu nome tem ao todo {} letras sem os espaços'.format(nomeSemEspaços))
nome1= nome.split() 
primeiroNome= len(nome1[0])
print('Seu primeiro nome tem {} letras'.format(primeiroNome))